FROM node:alpine
WORKDIR /app
COPY src/main/java/com/factorial/metrics/web/frontend/package.json .
COPY src/main/java/com/factorial/metrics/web/frontend/package-lock.json .
COPY src/main/java/com/factorial/metrics/web/frontend ./
RUN npm i
CMD ["npm", "run", "start"]
