version: '3.8'
services:
  metrics-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metrics
    ports:
      - "8080:8080"

  client:
    build:
      dockerfile: src/main/java/com/factorial/metrics/web/frontend/Dockerfile-front
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - metrics-api
